export const ActionTypes = {
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    FETCH_SELECTED_PRODUCT: 'FETCH_SELECTED_PRODUCT',
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}